### ISSUE TITLE
Epic PredatorPrey Enhancements

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/Abmarl#10]
Consolidation of all open efforts related to the predator prey environment.

- [ ] Grid mode communication #6
How do the observations change in grid mode with communications?

- [ ] Distance observation mode see edge #8
Should the agents see the edge of the map in distance observation mode?

- [x] Stochasticity #51, #36
Stochasticity in the observations and actions, especially action effectiveness.

- [x] Broadcast communication. #65 
All agents within some distance can receive the message, with some randomness. In addition, all agents within some distance (can be larger than message distance) can see the broadcaster's location.

- [x] Highly-componentized design of environments
PredatorPreyEnv currently processes some interactions between the predators and prey. Each agent can move around on the grid and the predators can attack the prey. The prey can also harvest resources. This could be split up into 3 components: a movement handler, an agent-agent-interaction handler, and an agent-environment-interaction handler. This is a significant redesign, so it should be considered very carefully and not as part of the main development push.

- [x] Add the ability to specify agent start positions
Agents are just started randomly in the grid. For reproducibility, including in the test suite, we should add the ability to specific the agents' starting locations.

- [x] Agent Health
Each agent is given some health. This health degenerates slowly over time as the agent grows hungrier. The health can also decrease if the agent is attacked. If the health reaches zero, then the agent dies. Health can also increase by eating
resources. For prey, that means foraging. For predators, that means eating prey.
In the future, if health increases above some maximum limit, the agent can reproduce.

- [x] Attack Strength
We already have attack range, which is the number of squares away the attack is effective. Now, we want attack strength, which indicates how much health the attacked agent will lose when attacked. Prey also have an attack strength in the sense of how much of the resource they will deplete when they eat it.

- [x] Entropy
The amount of health the agent loses each time it takes an action.

- [x] Revival
The amount of health the agent will receive when it consumes a resource.
