### ISSUE TITLE
Attack variations

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/Abmarl#68]
**Attack Types**
- [x] Binary Attack -- single random agent
This is where the agent blindly chooses attack or not. The Actor randomly picks an attackable agent in the attack range. We already have this. Action space is `Binary`
- [x] Selective Attack
This is where the agent chooses which cells in its attack range to attack. Action space is
`Box(0, 1, (2 * attack_range + 1,2 * attack_range + 1), int)`
- [x] K-Restricted Selective Attack.
This is where the agent chooses which cells in its attack range to attack, up to K cells. If the agent must choose a different cell each time, then we have sum over N choose i options, where N is `(2 * attack_range + 1)^2` and i goes from 1 to K. The action space would be `MultiDiscrete(N+1, N, N-1, ...)`, up to K entries. Each element in the attack vector would be converted to a grid cell or no attack.
If it can attack the same cell twice, then this goes up to `(N+1)^K`, where we have N+1 because the agent can choose not to use one of its K attacks. The action space would be `MultiDiscrete(N+1, N+1, N+1, ...)` up to K entries. Each element of the attack vector would be converted to a grid cell or no attack.
* Min-max attack (MAYBE LATER)
Here, the agent can attack between a minimum range and a maximum range. So it can attack up to max cells away, and must attack at least min cells away. The attack grid can be broken into four pieces, and we can apply the same logic above to each of those pieces.
- [x] Encoding based attack
The `attack_mapping` parameter specifies which agent types can attack other agent types. We use this in the simulation dynamics already, and I think I can make an attack actor that makes each channel explicit. This would use the binary attack logic under the hood.

**Variations**
Each of the attack types above can have variations. For example,
- [x] Agents can have a number of attacks, which the attack actors can interpret for their own processing.
* The ability to attack agents in masked cells. That is to say, does masking block the attack? Right now, it does, but should it? This should be done in #202.

We can have many more variations, but this is a good starting point.

**Design**
- [x] Each actor shares a common structure and set of attributes. We should combine them.
- [x] Determining the attack is unique among the actors, but even this still follows more or less the same structure. We should consider how we can combine this together as well.

**Comment by rusu24edward** [comment]
For the K-Restricted Selective Attack, we will not have the feature where the agent must choose a different cell each time.

**Comment by rusu24edward** [comment]
Some of the variation described above can be captured by the `number_of_attacks` parameter.

**Comment by rusu24edward** [comment]
Min-max attack may be interesting in the future, but for now we're not going to implement it.

Should focus on the variations now, specifically with regards to the number of attacks parameter
