### ISSUE TITLE
Monte Carlo Algorithms to work with AgentEnvironment interface

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/Abmarl#7]
The Monte Carlo algorithms only work with the gym environment interface, which is made explicit in #62. We should enable multi-agent monte-carlo learning. We can approach it in the following way:
- [X] Make the monte carlo algorithms work with AgentEnvironment interface, but enforce that there is only one agent in the dictionary since we only train a single policy.
- [ ] Support multiple-agents in the AgentEnvironment as long as they all train different policies. This is easier than the same policy because we have exclusivity in the SAR tuples. If there are multiple experiences training the same policy, then we have to start paying attention to how we combine the experiences from other agents into one update.
- [ ] Support multiple-agents in the AgentEnvironment that can train one or many policies.

**Comment by rusu24edward** [comment]
`AgentEnvironment` interface is obsolete since we went with `AgentBasedSimulation` and `SimulationManager`. The ideas here are still valid, though. #238 shows us how to deal with a multi-policy trainer, which I think is the right way to go. #244 covers the many-to-one policy training.
